### ISSUE TITLE
Record internal and external audio?

### ISSUE THREAD

**Issue by sdushantha** [GaugeK/blaze#1]
Really like this script! I think I would be able replace SimpleScreenRecorder with `blaze` if it could record the internal and external audio at the same time.

I managed to get the external (microphone) audio recording working by setting the `-i` flag in `ffmpeg` to `default`, but was not able to get both internal and external working at the same time. Would be able to implement this to `blaze`?

**Comment by eepykate** [comment]
Sadly I don't think there's an easy way. I also have no microphone so I wouldn't be able to test.
