### ISSUE TITLE
Always get "multiple instances" error message

### ISSUE THREAD

**Issue by Barbaross93** [GaugeK/blaze#3]
As the title says, every time I run scr, I get the error message even when no other scr process is running. I'm not sure how to fix it as I don't know what `${0##*/}` refers to.

**Comment by Barbaross93** [comment]
well, I think I get what that variable is doing now, and with a little debugging, I'm finding that it's always null or 0 with the `-c` flag. I have no idea why it would be the case.

**Comment by eepykate** [comment]
Currently on my phone so can't help much, I'll look into the issue tomorrow.

>  I don't know what ${0##*/} refers to.

$0 is the script's path,
For example `/usr/local/bin/scr`
(${0} is the same as $0)

The `##*/` deletes everything before the last slash,
So the example should be shortened to `scr`

---

And I'll probably change the way I do process checking, I don't remember
being too proud of it (but yet again I barely remember what I did)

**Comment by eepykate** [comment]
Alright.

@Barbarossa93 Above the error checking line (166), can you put

```
pgrep -x "${0##*/}"; printf "\n$$\n"; exit
```

Just so I can see the output of pgrep (and the script's pid) - it *should* give 2 occurrences of the same number.

Also, to be clear, you're on the latest commit?

**Comment by Barbaross93** [comment]
For some reason on my setup, I only see one number.  Yes, I'm on the latest commit.

I checked out phisch's giph and tried `pgrep -f "bash.+${0##*/}"` instead of `pgrep -x "${0##*/}"` and now I see two of the same number. Seems like an issue with process naming?

**Comment by eepykate** [comment]
Perhaps.

How are you running scr?

**Comment by Barbaross93** [comment]
I'm seeing the error crop up within a terminal. My shell is zsh if that matters

**Comment by eepykate** [comment]
@Barbarossa93 I mean, are you running it like `scr`, `bash scr`, or something else?

I assume that scr is in $PATH?

**Comment by Barbaross93** [comment]
Oh sorry, yes, I'm simply running as `scr -c -e` with it in my $PATH

**Comment by eepykate** [comment]
Honestly I have no idea what the issue could be, but I'll keep thinking.

@Barbarossa93 one quick thing though, can you try installing `dash`, then changing the /bin/sh symlink to use it (`sudo ln -sf /bin/sh dash`), then try that line i told you to add again?

**Comment by Barbaross93** [comment]
So instead of changing the symlink, I just changed the shebang line to point to dash (I hope that's fine, let me know if you still want me to try with the symlink). It now works as expected. I thought bash was fully POSIX compliant, I guess it might not be?

Further, changing the shebang to point to zsh also works.

**Comment by eepykate** [comment]
> I thought bash was fully POSIX compliant, I guess it might not be?
It's far from it.  I don't generally remember the times it breaks, but
a common example is `echo` needing `-e` in bash for the default POSIX
behavior.

Dash isn't fully POSIX either, but it is POSIX-compliant.
For example, dash supports `[[ stuff ]]`, which was added in bash.

Anyway, now I know the issue lies with bash so I know where to look.

**Comment by eepykate** [comment]
Alright, looks like bash gives `$(subshells)` another PID with the same process name as the script.

```
 > scr # bash
script's pid
28730
no subshell
28730
subshell
28730
28736
 > scr # dash
script's pid
28797
no subshell
28797
subshell
28797
 >
```

**Comment by eepykate** [comment]
> Alright, looks like bash gives $(subshells) another PID with the same process name as the script.

... but only when using an empty `trap`

Changing `trap '' INT` to `trap ':' INT` seems to work.  (`:` is a nop, similar to `true`)

god, that's an interesting bug.

**Comment by Barbaross93** [comment]
Wow, that is a bizarre bug! Looks like it works now, so thanks for figuring that out! I would never have guessed.

**Comment by eepykate** [comment]
Honestly, thanks for reporting.  This was rather interesting.
